# Generated by Django 4.1.3 on 2022-11-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_chipset",
                    models.CharField(max_length=50, verbose_name="Чипсет"),
                ),
            ],
            options={
                "verbose_name": "Аудио чипсет",
                "verbose_name_plural": "Аудио чипсеты",
            },
        ),
        migrations.CreateModel(
            name="BackPannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.TextField(verbose_name="Информация")),
            ],
            options={
                "verbose_name": "Задняя панель",
                "verbose_name_plural": "Задние панели",
            },
        ),
        migrations.CreateModel(
            name="Cpu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Наименование")),
            ],
            options={"verbose_name": "Сокет", "verbose_name_plural": "Сокеты",},
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Наименование")),
                ("height", models.SmallIntegerField(verbose_name="Высота")),
                ("weight", models.SmallIntegerField(verbose_name="Ширина")),
            ],
            options={
                "verbose_name": "Форм фактор",
                "verbose_name_plural": "Форм факторы",
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Memory_Freq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freq", models.CharField(max_length=10, verbose_name="Частота")),
            ],
            options={
                "verbose_name": "Частота памяти",
                "verbose_name_plural": "Частоты памяти",
            },
        ),
        migrations.CreateModel(
            name="Memory_Max_Sizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_size", models.SmallIntegerField(verbose_name="Объем")),
            ],
            options={
                "verbose_name": "Макс. объем",
                "verbose_name_plural": "Макс. объемы",
            },
        ),
        migrations.CreateModel(
            name="Memory_Slots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.SmallIntegerField(verbose_name="Кол-во")),
            ],
            options={
                "verbose_name": "Кол-во слотов",
                "verbose_name_plural": "Кол-во слотов",
            },
        ),
        migrations.CreateModel(
            name="Memory_Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="Тип")),
            ],
            options={
                "verbose_name": "Тип памяти",
                "verbose_name_plural": "Типы памяти",
            },
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adapter", models.CharField(max_length=50, verbose_name="Адаптер")),
                ("speed", models.SmallIntegerField(verbose_name="Срокость адаптера")),
            ],
            options={
                "verbose_name": "Сетевой адаптер",
                "verbose_name_plural": "Сетевые адаптеры",
            },
        ),
        migrations.CreateModel(
            name="Pci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="Название")),
            ],
            options={"verbose_name": "Тип PCI", "verbose_name_plural": "Типы PCI",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(default="", max_length=100, verbose_name="Модель"),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.audio",
                    ),
                ),
                (
                    "back_panel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.backpannel",
                    ),
                ),
                (
                    "cpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.cpu",
                    ),
                ),
                (
                    "form_factor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.factor",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.memory",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.network",
                    ),
                ),
                (
                    "pci",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.pci",
                    ),
                ),
            ],
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты",},
        ),
        migrations.AddField(
            model_name="memory",
            name="max_size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.memory_max_sizes",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="memory_freq",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.memory_freq",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="memory_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.memory_slots",
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="memory_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.memory_types",
            ),
        ),
    ]
