# Generated by Django 4.1.3 on 2022-11-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={"verbose_name": "Память", "verbose_name_plural": "Память"},
        ),
    ]
