# Generated by Django 4.1.3 on 2022-11-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_memory_freq_freq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=40, verbose_name="Название схемы"),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Схема")),
            ],
            options={"verbose_name": "Схема", "verbose_name_plural": "Схемы",},
        ),
        migrations.AlterField(
            model_name="factor",
            name="height",
            field=models.FloatField(verbose_name="Высота"),
        ),
        migrations.AlterField(
            model_name="factor",
            name="weight",
            field=models.FloatField(verbose_name="Ширина"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.schema",
            ),
        ),
    ]
