# Generated by Django 4.1.3 on 2022-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_schema_alter_factor_height_alter_factor_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="image",
            field=models.ImageField(
                upload_to="static/catalog/images", verbose_name="Схема"
            ),
        ),
    ]
