# Generated by Django 4.1.3 on 2022-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_schema_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="image",
            field=models.ImageField(
                upload_to="static/catalog/media", verbose_name="Схема"
            ),
        ),
    ]
