# Generated by Django 4.1.3 on 2022-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_schema_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop_url",
            field=models.TextField(default="url", verbose_name="Ссылка на покупку"),
        ),
    ]
